version: '3'
services:
  fluentd:
        build: ./fluentd
        ports:
          - "24224:24224"
          - "24224:24224/udp"
        networks:
          - logs
  elasticsearch:
        image: elasticsearch
        expose:
          - 9200
        ports:
          - "9200:9200"
        networks:
          - logs
  kibana:
        image: kibana
        ports:
          - "5601:5601"
        networks:
          - logs
networks:
  logs: