version: 0.2

phases:
  install:
    commands:
      - apt-get update
      - apt-get install -y jq curl
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
      - unzip ./sonar-scanner-cli-4.6.2.2472-linux.zip
      - export PATH=$PATH:./sonar-scanner-4.6.2.2472-linux/bin/
  pre_build:
    commands:
      - rbenv install 2.4.10
      - rbenv global 2.4.10
  build:
    commands:
      - sonar-scanner -Dsonar.organization=ybudnyi -Dsonar.projectKey=Dashvis -Dsonar.sources=. -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=de955f503aa4db82aad3dbf9ce5a1c8cceb1f54e
      - sleep 5
      - curl https://sonarcloud.io/api/qualitygates/project_status?projectKey=Dashvis > analysis.json
      - cat analysis.json