---
global:
  scrape_interval: '5s'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
        - 'localhost:9090'

  - job_name: 'node'
    static_configs:
      - targets:
        - '10.26.0.242:9100'
  - job_name: 'cadvisor'
    static_configs:
      - targets:
        - '10.26.0.242:8080'