---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashvis
  labels:
    app: dashvis
    component: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dashvis
      component: app
  template:
    metadata:
      name: app-pod
      labels:
        app: dashvis
        component: app
    spec:
      containers:
      - image: ybudnyi/demo2:new
        name: app