---
apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app: dashvis
    component: app
spec:
  type: NodePort
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: dashvis
    component: app