---
- name: Change config file
  become: true
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644
- name: Change hosts file
  become: true
  template:
    src: hosts.j2
    dest: /etc/hosts
- name: Restart haproxy
  systemd:
    name: haproxy
    state: restarted