---
# tasks file for gogs
- name: Disable firewall
  systemd:
    name: firewalld 
    state: stopped
    enabled: yes
- include: gogspackages.yml
- name: Start mariadb service
  systemd:
    name: mariadb
    state: started
    enabled: yes
- include: gogsdb.yml
- include: goinstall.yml
- name: Add user git
  user:
    name: "{{ user }}"
    comment: "{{ comment }}"
#    home: /home/"{{ user }}"
- include: appinstall.yml

